# Secure the CMS with letsencrypt SSL
# Replace the MY_DOMAIN_NAME variable below with the name you want
# the SSL certificate issued for. Replace the same name in to the 
# letsencrypt -> command section, as well as your email address
# for letsencrypt
#
# Code from https://bitbucket.org/automationlogic/le-docker-compose.git
# 
# Once setup, you need to periodically renew your SSL cert as follows
# docker-compose run letsencrypt
# docker exec xibo-docker_nginx_1 nginx -s reload
#
# You could create a scheduled task/cron job to do so.

version: "2"

services:
    nginx:
        build: containers/nginx-image
        links:
            - letsencrypt
            - cms-web
        environment:
            - MY_DOMAIN_NAME=cms.example.org
        mem_limit: 256m
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes_from:
            - letsencrypt
    letsencrypt:
        image: quay.io/letsencrypt/letsencrypt:latest
        command:  bash -c "sleep 6 && certbot certonly --standalone -d cms.example.org --text --agree-tos --email user@example.org --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
        entrypoint: ""
        volumes:
            - /etc/letsencrypt
            - /var/lib/letsencrypt
        ports:
            - "80"
            - "443"
        environment:
            - TERM=xterm
    cms-web:
        ports:
            - "80"
