#!/bin/bash

# Extract and move the archive
tar xf /var/www/xibo-cms-1.8.0-alpha3.tar.gz -C /var/www
mv xibo-cms-1.8.0-alpha3/* xibo

# Populate the DB

# Write settings.php

# Set LIBRARY_LOCATION

# Set admin username/password (passed in)

# Set XMR public/private address
